@baseUrl = http://localhost:5000
@urlPath = api/v1


POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Loki",
  "password": "Qaz12wsx",
  "email": "gray.grifon@gmail.com",
  "avatarColor": "green",
  "avatarImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHZAq08u4YaR0Jsu2CgeptdxC74y-9QEeFYEAb6YHP&s"
}
