@baseUrl = http://localhost:5000
@urlPath = api/v1


POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Loki",
  "password": "Qaz12wsx",
  "email": "gray.grifon@gmail.com",
  "avatarColor": "green",
  "avatarImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHZAq08u4YaR0Jsu2CgeptdxC74y-9QEeFYEAb6YHP&s"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Loki",
  "password": "Qaz12wsx"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "gray.grifon@gmail.com"
}
###
POST {{baseUrl}}/{{urlPath}}/reset-password/
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "qwerty",
  "confirmPassword":  "qwerty"
}


